name: ci

on:
  pull_request:
    branches: [master]

jobs:
  common:
    uses: TokTok/ci-tools/.github/workflows/common-ci.yml@master

  build-msvc:
    strategy:
      matrix:
        version: [2019, 2022]
    runs-on: windows-${{ matrix.version }}
    env:
      VCPKG_ROOT: "C:/vcpkg"
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Configure CMake
        run: cmake --preset windows-default
      - name: Build
        run: cmake --build _build -j $([int]$env:NUMBER_OF_PROCESSORS+2)
      - name: Test
        run: |
          cd _build
          ctest -j50 --output-on-failure --rerun-failed --repeat until-pass:6 --build-config Debug

  build-windows:
    strategy:
      matrix:
        bits: [32, 64]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Cross compilation
        run: .github/scripts/cmake-win${{ matrix.bits }} script
